-- AlterTable
ALTER TABLE `Settings` MODIFY `heroTitle` TEXT NULL,
    MODIFY `heroDescription` TEXT NULL,
    MODIFY `heroImage` LONGTEXT NULL,
    MODIFY `heroImage1` LONGTEXT NULL,
    MODIFY `heroImage2` LONGTEXT NULL,
    MODIFY `heroImage3` LONGTEXT NULL,
    MODIFY `heroImage4` LONGTEXT NULL,
    MODIFY `missionIntroTitle` TEXT NULL,
    MODIFY `missionIntroDescription` TEXT NULL,
    MODIFY `missionImage` LONGTEXT NULL,
    MODIFY `missionTitle` TEXT NULL,
    MODIFY `missionDescription` TEXT NULL,
    MODIFY `visionTitle` TEXT NULL,
    MODIFY `visionDescription` TEXT NULL,
    MODIFY `valuesTitle` TEXT NULL,
    MODIFY `valuesDescription` TEXT NULL,
    MODIFY `volunteerIntroTitle` TEXT NULL,
    MODIFY `volunteerIntroDescription1` TEXT NULL,
    MODIFY `volunteerIntroDescription2` TEXT NULL;
